### PR TITLE
Proposed changes in: Element.py, Model.py, Readme and a new example added

### PR DESCRIPTION
**Pull request by caiuamelo**
Firstly, great work!

Element.py: CAX4 element added to the element list
Model.py: Small fix for a KeyError exception.
Readme: Few typos corrected
New example: a example concerning the visualization of displacements was added in the Examples folder.

### CODE REVIEW

**Comment by cristobaltapia** [comment]
Hi @caiuamelo ,
thanks for this PR! I am happy that someone found this useful besides me :D . There are some small details I would like to be addressed before merging all the changes. I will make some comments on each commit.

**Review by cristobaltapia — CHANGES_REQUESTED** [review]
Could you make sure that only the added lines are marked as new? It looks as if the whole file had been edited.

**Review by cristobaltapia — CHANGES_REQUESTED** [review]
I think this would be a good point to start using exceptions. Maybe something like:
```
try:
    elem_ids = self.elem_output[step][inc][var].keys()
except KeyError:
    Print(f"Requested output variable {var} not present in the model.")
```

**Review by cristobaltapia — APPROVED** [review]
Thanks!

**Review by cristobaltapia — CHANGES_REQUESTED** [review]
This is really great! My original idea was exactly to have these kind of examples, but I didn't find the time for it. So thanks! I would only have one small change here: in the `displacement_visualization.py` file I would delete the `color="white"` parameter in line 12, as it is not really needed when plotting results. Otherwise, great addition!

**Comment by cristobaltapia** [comment]
Sorry for all the comments and reviews... I have little experience handling PRs :P

**Comment by caiuamelo** [comment]
Thanks for showing interest in my suggestions @cristobaltapia!

> Could you make sure that only the added lines are marked as new? It looks as if the whole file had been edited.

OK. Reverted the commit and tried to recommit it and push.
 
> I think this would be a good point to start using exceptions. Maybe something like:
> ```
> try:
>     elem_ids = self.elem_output[step][inc][var].keys()
> except KeyError:
>     Print(f"Requested output variable {var} not present in the model.")
> ```

Added this block, instead of the previous code. 

> This is really great! My original idea was exactly to have these kind of examples, but I didn't find the time for it. So thanks! I would only have one small change here: in the `displacement_visualization.py` file I would delete the `color="white"` parameter in line 12, as it is not really needed when plotting results. Otherwise, great addition!

Done.

I am still learning how to use Git/Github. I am not so familiar with all the process, sorry for these issues.
Thanks again!

**Comment by cristobaltapia** [comment]
This looks good to me. Thanks for your contribution!
And don't worry, I am also not a Github expert, so I have to learn too ;)

**Comment by cristobaltapia** [comment]
For future contributions, it is better to create different pull requests (PR) for each feature, e.g. the addition of the new element in one PR, then the new example in another, and so on.

**Pull request merged**
