### PR TITLE
fixed some bugs and added new C3D10 tetra 10 nodes

### PR DESCRIPTION
**Pull request by escolano**
Please, consider merge my changes in your main branch.

I am using your pybaqus module to implement a .fil Abaqus result importer plugin for our GiD program (www.gidsimulation.com)
I have a first version of the GiD-pybaqus importer working, but with the related changes of my fork.

I attach Job-2-E-mod.fil that show the error related with first node nid==2 instead 1
[Job-2-E-mod_fil.zip](https://github.com/cristobaltapia/pybaqus/files/10961349/Job-2-E-mod_fil.zip)

and tetra_10.fil that has C3D10 tetrahedra quadratic missing implementitaon
[tetra_10_fil.zip](https://github.com/cristobaltapia/pybaqus/files/10961362/tetra_10_fil.zip)

Finally I attach a screenshot of GiD with the example Job-2-E-mod.fil imported
gid_import

### CODE REVIEW

**Comment by cristobaltapia** [comment]
Hey @escolano, thanks a lot for this pull request with the fixes and new features! Just by quickly looking at it, it looks very good. The only thing I am missing would be to implement the the extrapolation matrix for the C3D10 (I can help with that, but I am just a bit busy right now). This is used to extrapolate the results from the integration points to the nodes of each element. The C3D20R is also missing this... I just have not used those elements in a while.

I will try to come back to this as soon as possible. I am glad that you are finding this library useful enough to add it to you program.

**Comment by escolano** [comment]
Yes, I have implemented for the tetra10 moreless the same that I've seen in the hexa20.
In fact the extrapolation matrix is unneeded my own usage, I basically need the parsing step to import the Abaqus results data
(inside our code can do extrapolations from gauss points to nodes, and have all shape functions, and also its derivatives of some order)
In any case, if I have time, I will study how to fill your extrapolate_to_nodes function according to the VTK definitions

**Comment by cristobaltapia** [comment]
Hi @escolano, I just did some reviewing and it seems to work good (if I uncomment the lines I marked above). Why did you leave those lines commented? Once we clear that point I would say that we are good to merge :)

**Comment by escolano** [comment]
Sorry, I cannot find where are 'the commented lines marked above' that you are talking about.

**Comment by cristobaltapia** [comment]
I mean lines 710 to 715 in `model.py`. You have written this:

```py
            #can replace here the kmap used for get_node_coords of do it outside knowing kmap 
            #node_ids = sorted(list(self.nodes.keys()))
            #new_node_ids = np.arange(1, len(node_ids) + 1, 1)
            ## Map new indices to old indices
            #kmap = {ix: k for k, ix in zip(new_node_ids, node_ids)}
```

And it is commented. When I use your code like this, then the example [Job-2-E-mod_fil.zip](https://github.com/cristobaltapia/pybaqus/files/10961349/Job-2-E-mod_fil.zip) does not work. If I uncomment it, then it works.

**Comment by escolano** [comment]
ok, now I understand you.
When nodes are not numbered from 1 to n like the example [Job-2-E-mod_fil.zip] it is necessary to map the old and new ids of nodes, and this map must be also applied:
(a)-to elements
(b)-to nodal results

In my external usage I am only getting all the information of nodes+elements+results from your package and with the nodes I am getting the kmap, then I am renumbering (a) and (b) by myself (e.g. I am not using the package features to draw)

My commented code worked well, and it do (a) but not (b), then in any case I need to know kmap and do externally the step (b)

Then to be 'less invasive' with your code I decided to avoid it, and left commented (I don't deleted because seemed interesting, as you noticed). 
I agree that it can be uncommented again (and then externally I can simply do (b))

In the future could be interesting to fix also the nodal results numeration in the package

Note: In my plugin am collecting all the Abaqus information with this small Python function:
```
def my_pybaqus_read_results(filename):
    #to avoid that numpy truncate the printed representation of its arrays
    np.set_printoptions(threshold=np.inf)
    model=pybaqus.open_fil(filename)
    nodes,kmap=model.get_node_coords(return_map=True)    
    nodes_map_ids=np.empty(len(kmap),dtype=int)
    i=0
    for node_id in kmap.values():
        nodes_map_ids[i]=node_id
        i+=1
    cells=model.get_cells()
    elements=cells[0]
    element_types=cells[1]
    #by now only results of time step 1
    incre=1
    nodal_result_all_steps = []
    for step in model.steps.keys():
        nodal_result_names=list(model.nodal_output[step][incre].keys())
        nodal_result_step = []
        for nodal_result_name in nodal_result_names :
            nodal_result_step.append(nodal_result_name)
            nodal_result_step.append(model.nodal_output[step][incre][nodal_result_name])
        nodal_result_all_steps.append(step)
        nodal_result_all_steps.append(nodal_result_step)
    elem_result_all_steps = []
    for step in model.steps.keys():
        elem_result_names=list(model.elem_output[step][incre].keys())
        elem_result_step = []
        for elem_result_name in elem_result_names :
            elem_result_step.append(elem_result_name)
            elem_result_step.append(model.elem_output[step][incre][elem_result_name])
        elem_result_all_steps.append(step)
        elem_result_all_steps.append(elem_result_step)
    return [nodes,nodes_map_ids,elements,element_types,nodal_result_all_steps,elem_result_all_steps]
```

**Comment by cristobaltapia** [comment]
Thanks @escolano . I have merged your PR as is. There are some things that I have to look later, like correctly mapping the nodal results. As a general remark for (hopefully) future PR, I would recommend for you to create a local branch and make a PR for each separate issue. For example, the implementation of the QuadraticTetra element could have been done independent from the changes corresponding to the issue of nodes not starting at 1. Then it is easier to manage the different fixes. :)

**Comment by escolano** [comment]
Ok, in fact instead of a branch by issue I did a single commit by issue with its comment explaining it, then a cherry pick of each commit is an easy way to accept or not each one

e.g. implement of quadratic tetra was a commit and fix numeration issues other commit (really I started with a local copy with all changes and fixes, but commited them to github incrementally and issue by issue)

 

Enrique

**Pull request merged**
